# deployment.yaml 예시
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cgv-server
  namespace: cgv-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cgv-server
  template:
    metadata:
      labels:
        app: cgv-server
    spec:
      containers:
      - name: cgv-server
        image: duswjd/cgv-server:1e62b3a
        ports:
        - containerPort: 8080

