apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: cgv-server
  namespace: cgv-backend
spec:
  #replicas: 4
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: { duration: 30s }
        - setWeight: 50
        - pause: { duration: 60s }
        - setWeight: 100
  selector:
    matchLabels:
      app: cgv-server
  template:
    metadata:
      labels:
        app: cgv-server
    spec:
      tolerations:
      - key: "karpenter-only"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      containers:
      - name: cgv-server
        image: 911167907616.dkr.ecr.ap-northeast-2.amazonaws.com/cgv-server:4227da1
        ports:
        - containerPort: 8080
        resources:                     # ✅ 추가
          requests:
            cpu: "400m"
          limits:
            cpu: "600m"
