apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: cgv-server  # 앱 이름
  namespace: cgv-backend        # 실제 사용하는 네임스페이스로 변경
spec:
  replicas: 3
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: { duration: 30s }
        - setWeight: 50
        - pause: { duration: 60s }
        - setWeight: 100
  selector:
    matchLabels:
      app: cgv-server   # Deployment에 사용되던 라벨과 일치해야 함
  template:
    metadata:
      labels:
        app: cgv-server
    spec:
      topologySpreadConstraints:   # 👈 여기!
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: cgv-server
      containers:
        - name: cgv-server
          image: 911167907616.dkr.ecr.ap-northeast-2.amazonaws.com/cgv-server:9a11360
          ports:
            - containerPort: 8080
